#let entry-list = (
  (
    key: "ai",
    short: "AI",
    long: "Artificial Intenligence",
    description: "",
  ),
  (
    key: "ann",
    short: "ANN",
    long: "Artificial Neural Network",
    description: "",
  ),
  (
    key: "snn",
    short: "SNN",
    long: "Spiking Neural Network",
    description: "",
  ),
  (
    key: "mlp",
    short: "MLP",
    long: "Multi Layer Perceptron",
    description: "",
  ),
  (
    key: "llm",
    short: "LLM",
    long: "Large Language Model",
    description: "",
  ),
  (
    key: "gpt",
    short: "GPT",
    long: "Generative Pre-trained Transformer",
    description: "",
  ),
  (
    key: "rnn",
    short: "RNN",
    long: "Recurrent Neural Network",
    description: "",
  ),
  (
    key: "lstm",
    short: "LSTM",
    long: "Long Short-Term Memory",
    description: "",
  ),
  (
    key: "xor",
    short: "XOR",
    long: "eXclusive OR",
    description: "",
  ),
  (
    key: "cnn",
    short: "CNN",
    long: "Convolutional Neural Network",
    description: "",
  ),
  (
    key: "cpu",
    short: "CPU",
    long: "Central Processing Unit",
    description: "",
  ),
  (
    key: "gpu",
    short: "GPU",
    long: "Graphics Processing Unit",
    description: "",
  ),
  (
    key: "cmos",
    short: "CMOS",
    long: "Complementary Metal-Oxide-Semiconductor",
    description: "",
  ),
  (
    key: "ap",
    short: "",
    long: "action potential",
    description: "Voltage potential in the neuron cell membrane that propagates trough the neurons axon and to its synapses",
  ),
)
